[package]
name = "cortex-m-spa-model"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.1.0", features = ["deref"] }
proto-hal-model = { git = "https://github.com/adinack/proto-hal" }
